// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qkWw1GqfHFR35tc38NnRT2caot8ueg8',
    appId: '1:1073213289680:web:2f159036998aded5419ad5',
    messagingSenderId: '1073213289680',
    projectId: 'akjol-547a0',
    authDomain: 'akjol-547a0.firebaseapp.com',
    storageBucket: 'akjol-547a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4OvmntuqPt2HU-DoVN9gb_BKWqrPO-E',
    appId: '1:1073213289680:android:1d2af75a6a5358ff419ad5',
    messagingSenderId: '1073213289680',
    projectId: 'akjol-547a0',
    storageBucket: 'akjol-547a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxpTdK-Tn3W41JyTit5i1RWJ0FObrwoqU',
    appId: '1:1073213289680:ios:0b8a451d89cff90f419ad5',
    messagingSenderId: '1073213289680',
    projectId: 'akjol-547a0',
    storageBucket: 'akjol-547a0.appspot.com',
    iosClientId: '1073213289680-sblvubm3resntvf62t7bov10jtcqoefv.apps.googleusercontent.com',
    iosBundleId: 'com.example.akjol',
  );
}
